### ISSUE TITLE
issue with canvas width not modolo of 4

### ISSUE THREAD

**Issue by jbreizh** [samber/canvas-to-bmp#2]
hello, it seems you reuse this code https://stackoverflow.com/questions/29652307/canvas-unable-to-generate-bmp-image-dataurl-in-chrome for 24bit

i reuse your code for my project but their is a problem when the width of the canvas is not a modolo of 4 (i think i just made a few test) . For exemple 116 and 120 is ok but 117-118 and 119 are scramble.
The original method for 32 bit work ok. Can you test it ? I can't find the problem in my code....
If you re french, i am french, so answer me in french it will be simple for me.
Thanks

here my project : https://github.com/jbreizh/ImagePainting/blob/master/android/PhoneGap/www/js/canvastobmp.js

**Comment by samber** [comment]
Hi @jbreizh 

Can you tell me more about your issue ?

Picture width is calculated in pixel. When you use 24bits, you must multiply by 3 to get weight of a line of pixels.

**Comment by jbreizh** [comment]
Thanks for the answer. It's little complicated to show the problem in the right way as it s just a part of my complete project and i don't reuse directly your code, but a modify version, but anyway i try to make you a "short" exemple to show my problem (in zip file)
CORS is no happy with this exemple, just try it with :
` chromium --user-data-dir=/tmp/ --disable-web-security`
I rotate the picture in the canvas but i don't thinks it's the problem (canvas is showing right) but if you set numPixels = 118; the result is scramble and  numPixels = 120; the result is good.
[test.zip](https://github.com/samber/canvas-to-bmp/files/3941091/test.zip)

**Comment by jbreizh** [comment]
Some result (github doesn't want bmp file)
[Downloads.zip](https://github.com/samber/canvas-to-bmp/files/3941094/Downloads.zip)

**Comment by samber** [comment]
Ok, looks like I need more investigations.

My spare time is getting very rare. If you can wait 1 or 2 months, ping me back here.

If you need a fix ASAP, i'm available for freelancing (50€/h).

Sorry :-(

**Comment by jbreizh** [comment]
ah don't worry i got it. I found a spec that say "pad row size to a multiple of 4 bytes ". So it was not a problem for 32 bit but for 24 bit it is one. So i change the line :
 `stride = Math.floor((24 * w + 23) / 24) * 3, // row length incl. padding`
to
```
var stride = w3;
if (stride%4 != 0) stride += (4 - stride%4); // row length incl. padding
```
and if i am right each row are 4 multiple now and it seems to work.
Thanks for your time.

![BMPfileFormat](https://user-images.githubusercontent.com/2498942/70477097-5fc18e80-1ad8-11ea-8e98-0b1b0f6e35fe.png)

**Comment by samber** [comment]
\o/

This is the meaning of "incl. padding". ;)

Can you write a small PR for that please ?

**Comment by jbreizh** [comment]
ok improve version, i find this book :
![BMP](https://user-images.githubusercontent.com/2498942/70523395-40138000-1b43-11ea-9b0f-95b83beb68f2.png)
so
`stride = Math.floor((32 * w + 31) / 32 ) * 4; // row length incl. padding`
was a reduce version of the formula so for 24 bits it's not :
` stride = Math.floor((24 * w + 23) / 24) * 3, // row length incl. padding`
but 
`stride = Math.floor((24 * w + 31) / 32 ) * 4; // row length incl. padding`

Do i really need to make a PR for this a line change?

**Comment by samber** [comment]
@jbreizh thanks for the fix.

Closing https://github.com/samber/canvas-to-bmp/commit/5dd8b84fe0816bfff26617b5a4c25e3189e11446
